version: "3"

services:
  web:
    image: "golang:1.14"
    ports:
      - "80:80"
      - "443:443"
    environment:
      # MYSQL_ROOT_PASSWORD: root
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    expose:
      - "80"
      - "443"
    volumes:
      - .:/go/src/docker
